from __future__ import annotations

import numpy as np
from scipy import sparse

from qcnn_lab.physics.operators import local_pauli, pauli_product
from qcnn_lab.physics.states import ground_state


def perturbed_tfim_hamiltonian(
    n: int,
    *,
    h: float = 1.0,
    j: float = 1.0,
    delta: float = 0.0,
    seed: int = 12345,
    periodic: bool = False,
) -> sparse.csr_matrix:
    """Disordered TFIM Hamiltonian: H = - sum J_i Z_i Z_{i+1} - sum h_i X_i.

    Disorder: J_i = J*(1 + eps_i), h_i = h*(1 + eta_i), with eps, eta ~ U[-delta, delta].
    When delta == 0.0, matches original unperturbed TFIM exactly.
    """
    if n < 2:
        raise ValueError("n must be >= 2")
    dim = 2**n
    rng = np.random.default_rng(seed)

    eps = rng.uniform(-delta, delta, size=n) if delta > 0 else np.zeros(n)
    eta = rng.uniform(-delta, delta, size=n) if delta > 0 else np.zeros(n)

    H = sparse.csr_matrix((dim, dim), dtype=complex)
    bonds = [(i, i + 1) for i in range(n - 1)]
    if periodic and n > 2:
        bonds.append((n - 1, 0))

    for idx, (i, j2) in enumerate(bonds):
        J_i = j * (1.0 + eps[idx])
        H -= J_i * pauli_product(n, {i: "Z", j2: "Z"})

    for i in range(n):
        h_i = h * (1.0 + eta[i])
        H -= h_i * local_pauli(n, i, "X")

    return H


def perturbed_cluster_hamiltonian(
    n: int,
    *,
    h: float = 1.0,
    j_cluster: float = 1.0,
    delta: float = 0.0,
    seed: int = 12345,
) -> sparse.csr_matrix:
    """Symmetry-preserving perturbed 1D cluster Hamiltonian.

    Protecting symmetry: Z_2 x Z_2 symmetry generated by:
        P_even = prod_{j even} X_j
        P_odd  = prod_{j odd}  X_j

    Perturbation terms:
    1. Bond disorder J_i = J*(1 + eps_i) on cluster terms Z_{i-1} X_i Z_{i+1}
    2. Local field disorder h_i = h*(1 + eta_i) on X_i
    3. Next-nearest X_i X_{i+2} interaction with coupling delta
    All terms commute with P_even and P_odd, strictly preserving the Z_2 x Z_2 SPT symmetry.
    """
    if n < 3:
        raise ValueError("n must be >= 3")
    dim = 2**n
    rng = np.random.default_rng(seed)

    eps = rng.uniform(-delta, delta, size=n) if delta > 0 else np.zeros(n)
    eta = rng.uniform(-delta, delta, size=n) if delta > 0 else np.zeros(n)

    H = sparse.csr_matrix((dim, dim), dtype=complex)

    # 3-site cluster stabilizer terms
    for i in range(1, n - 1):
        J_i = j_cluster * (1.0 + eps[i])
        H -= J_i * pauli_product(n, {i - 1: "Z", i: "X", i + 1: "Z"})

    # Transverse fields
    for i in range(n):
        h_i = h * (1.0 + eta[i])
        H -= h_i * local_pauli(n, i, "X")

    # Symmetry-preserving X_i X_{i+2} perturbation
    if delta > 0:
        for i in range(n - 2):
            H -= (delta * 0.5) * pauli_product(n, {i: "X", i + 2: "X"})

    return H


def perturbed_xxz_hamiltonian(
    n: int,
    *,
    delta_param: float = 1.0,
    j: float = 1.0,
    pert_strength: float = 0.0,
    seed: int = 12345,
    periodic: bool = False,
) -> sparse.csr_matrix:
    """Perturbed XXZ Hamiltonian preserving total S^z magnetization conservation (U(1) symmetry).

    H = sum J_i (X_i X_{i+1} + Y_i Y_{i+1} + Delta Z_i Z_{i+1}) + J_2 sum (X_i X_{i+2} + Y_i Y_{i+2})
    where J_i = J*(1 + eps_i) with eps_i ~ U[-pert_strength, pert_strength], J_2 = 0.5 * pert_strength.
    """
    if n < 2:
        raise ValueError("n must be >= 2")
    dim = 2**n
    rng = np.random.default_rng(seed)

    eps = rng.uniform(-pert_strength, pert_strength, size=n) if pert_strength > 0 else np.zeros(n)

    H = sparse.csr_matrix((dim, dim), dtype=complex)
    bonds = [(i, i + 1) for i in range(n - 1)]
    if periodic and n > 2:
        bonds.append((n - 1, 0))

    for idx, (i, j2) in enumerate(bonds):
        J_i = j * (1.0 + eps[idx])
        H += J_i * pauli_product(n, {i: "X", j2: "X"})
        H += J_i * pauli_product(n, {i: "Y", j2: "Y"})
        H += J_i * delta_param * pauli_product(n, {i: "Z", j2: "Z"})

    if pert_strength > 0 and n > 2:
        for i in range(n - 2):
            H += (pert_strength * 0.5) * pauli_product(n, {i: "X", i + 2: "X"})
            H += (pert_strength * 0.5) * pauli_product(n, {i: "Y", i + 2: "Y"})

    return H


def get_perturbed_ground_state(
    family: str,
    n_qubits: int,
    parameter: float,
    strength: float,
    *,
    seed: int = 12345,
) -> tuple[float, np.ndarray]:
    """Compute ground energy and state for a perturbed Hamiltonian."""
    if family == "tfim":
        H = perturbed_tfim_hamiltonian(n_qubits, h=parameter, delta=strength, seed=seed)
    elif family == "cluster":
        H = perturbed_cluster_hamiltonian(n_qubits, h=parameter, delta=strength, seed=seed)
    elif family == "xxz":
        H = perturbed_xxz_hamiltonian(n_qubits, delta_param=parameter, pert_strength=strength, seed=seed)
    else:
        raise ValueError(f"unknown family {family}")
    return ground_state(H)
